import { StyleSheet } from 'react-native';

export const TasksTheme = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(49, 57, 79, 0.08)',
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#31394F',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    marginLeft: 16,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  section: {
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#31394F',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#31394F',
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    color: '#787982',
    lineHeight: 24,
  },
  dateLabel: {
    fontSize: 12,
    color: 'rgba(49, 57, 79, 0.6)',
    marginBottom: 4,
  },
  taskViewContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  taskViewContent: {
    flex: 1,
    padding: 16,
  },
  taskImage: {
    width: '100%',
    height: 200,
    marginBottom: 16,
    borderRadius: 8,
  },
  teamContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  teamMember: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#7980FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  teamMemberText: {
    color: '#FFFFFF',
    fontWeight: '500',
  },
  addMemberButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8F9FD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusBadge: {
    backgroundColor: '#7980FF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  statusText: {
    color: '#FFFFFF',
    fontWeight: '500',
  },
  dueDateContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  dueDate: {
    fontSize: 16,
    color: '#31394F',
  },
  subtaskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FD',
    borderRadius: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#7980FF',
    marginRight: 12,
  },
  subtaskText: {
    fontSize: 16,
    color: '#31394F',
  },
  filterSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    marginTop: 8,
  },
  viewSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 12,
  },
  viewSelectorText: {
    marginLeft: 8,
    color: 'rgba(49, 57, 79, 0.8)',
    fontSize: 14,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 12,
  },
  filterButtonText: {
    marginLeft: 8,
    color: 'rgba(49, 57, 79, 0.8)',
    fontSize: 14,
  },
  calendarContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarMonth: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#31394F',
  },
  calendarControls: {
    flexDirection: 'row',
    gap: 16,
  },
  weekDaysContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
  },
  weekDayText: {
    fontSize: 12,
    color: 'rgba(49, 57, 79, 0.6)',
    width: 40,
    textAlign: 'center',
  },
  calendarDay: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 2,
  },
  calendarDayText: {
    fontSize: 14,
    color: '#31394F',
  },
  selectedDay: {
    backgroundColor: '#7980FF',
    borderRadius: 20,
  },
  selectedDayText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  todayDay: {
    backgroundColor: 'rgba(121, 128, 255, 0.1)',
    borderRadius: 20,
  },
  todayDayText: {
    color: '#7980FF',
    fontWeight: 'bold',
  },
  taskSection: {
    marginBottom: 32,
  },
  taskSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 20,
  },
  taskTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'rgba(49, 57, 79, 0.92)',
    marginRight: 8,
  },
  taskCount: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  taskCountText: {
    fontSize: 12,
    color: '#FFFFFF',
  },
  assignHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
  },
  assignText: {
    fontSize: 12,
    color: 'rgba(49, 57, 79, 0.5)',
  },
  taskItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    paddingLeft: 16,
    paddingRight: 16,
    borderBottomColor: 'rgba(49, 57, 79, 0.1)',
  },
  taskName: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(49, 57, 79, 0.92)',
  },
  taskDueDate: {
    fontSize: 12,
    color: 'rgba(49, 57, 79, 0.7)',
  },
  assigneeList: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  assigneeAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginLeft: -8,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 8,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  addSubtaskButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7980FF',
    padding: 16,
    borderRadius: 8,
    marginBottom: 24,
    gap: 8,
  },
  addSubtaskText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
