import { TextStyle, ViewStyle, ImageStyle, ColorValue } from 'react-native';

// Colors from CSS variables
export const colors = {
  surface: '#f5f5f5',
  white: '#fff',
  primary: '#7980ff',
  primaryBold: '#878dff',
  secondary: 'rgba(49, 57, 79, 0.7)',
  secondary2: '#b9bac3',
  success: '#5fd788',
  success2: '#54b24c',
  danger: '#f05a5a',
  warning: '#fcdb66',
  info: '#64bef1',
  light: '#e7e7e7',
  dark: '#1b325f',
  disable: '#d3b7a5',
  onSurface: '#151515',
  text: '#6f7582',
  text2: '#c9cbce',
  text3: '#343434',
  text4: '#d3d5da',
  text5: '#abadb2',
  line: '#e5e5e5',
  line2: '#d9d9d9',
  line3: '#dbdbdb',
  lineRgba: 'rgba(255, 255, 255, 0.1)',
  backdrop: 'rgba(49, 57, 79, 0.12)',
  bgProgress: 'rgba(21, 21, 21, 0.15)',
  rgbaPrimary: 'rgba(135, 59, 10, 0.1)',
  rgbaSuccess: 'rgba(30, 127, 17, 0.1)',
  rgbaDanger: 'rgba(225, 0, 0, 0.1)',
  rgbaWarning: 'rgba(255, 138, 0, 0.1)',
  rgbaInfo: 'rgba(167, 2, 103, 0.1)',
  rgbaDark: 'rgba(27, 50, 95, 0.1)',
  rgbaDisable: 'rgba(135, 59, 10, 0.1)',
  linerPrimary: ['#7980ff', '#bcc0ff'],
  linner1: ['rgba(135, 59, 10, 0)', '#2e1200'],
  background: '#F8F9FA',
  textPrimary: '#31394F',
  textSecondary: '#464D61',
  lightGray: '#F0F1F5',
} as const;

// Common styles used across the app
export const commonStyles = {
  container: {
    flex: 1,
    backgroundColor: colors.white,
  } as ViewStyle,
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    justifyContent: 'center',
  } as ViewStyle,
  headerTitle: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '700',
    textAlign: 'center',
  } as TextStyle,
  content: {
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 16,
    paddingRight: 16,
  } as ViewStyle,
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.secondary,
    marginBottom: 24,
  } as TextStyle,
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 12,
  } as ViewStyle,
  input: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: colors.secondary,
  } as TextStyle,
  eyeIcon: {
    padding: 8,
  } as ViewStyle,
  button: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  } as ViewStyle,
  buttonText: {
    color: colors.white,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  } as TextStyle,
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 24,
  } as ViewStyle,
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: colors.line,
  } as ViewStyle,
  dividerText: {
    marginLeft: 16,
    marginRight: 16,
    color: colors.secondary,
  } as TextStyle,
  socialButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
  } as ViewStyle,
  socialButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.line,
    justifyContent: 'center',
    alignItems: 'center',
  } as ViewStyle,
  socialIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  } as ImageStyle,
  bottomContainer: {
    marginTop: 32,
    alignItems: 'center',
  } as ViewStyle,
  bottomText: {
    fontSize: 16,
    lineHeight: 24,
  } as TextStyle,
  bottomLink: {
    color: colors.primary,
    fontWeight: '600',
  } as TextStyle,
} as const;

// Dashboard specific styles
export const dashboardStyles = {
  container: {
    flex: 1,
    backgroundColor: colors.background,
  } as ViewStyle,
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.white,
  } as ViewStyle,
  greeting: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: colors.textPrimary,
  } as TextStyle,
  subGreeting: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    marginTop: 4,
  } as TextStyle,
  content: {
    flex: 1,
    padding: 16,
  } as ViewStyle,
  progressSection: {
    flexDirection: 'row',
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  } as ViewStyle,
  progressCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  } as ViewStyle,
  progressInfo: {
    flex: 1,
    justifyContent: 'center',
  } as ViewStyle,
  progressTitle: {
    color: colors.white,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
  } as TextStyle,
  progressSubtext: {
    color: colors.white,
    fontSize: 12,
    lineHeight: 20,
    marginTop: 4,
  } as TextStyle,
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  } as ViewStyle,
  sectionTitle: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '700',
    color: colors.textPrimary,
  } as TextStyle,
  viewAll: {
    fontSize: 12,
    lineHeight: 20,
    color: colors.textSecondary,
  } as TextStyle,
  projectsScroll: {
    marginBottom: 24,
  } as ViewStyle,
  projectCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginRight: 16,
    width: 280,
  } as ViewStyle,
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  } as ViewStyle,
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
  } as ViewStyle,
  priorityBadge: {
    backgroundColor: colors.rgbaDanger,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  } as ViewStyle,
  priorityText: {
    color: colors.danger,
    fontSize: 11,
    lineHeight: 16,
  } as TextStyle,
  cardTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
  } as TextStyle,
  cardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  } as ViewStyle,
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  } as ViewStyle,
  metaText: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSecondary,
    marginLeft: 4,
  } as TextStyle,
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: colors.lightGray,
    borderRadius: 2,
    marginHorizontal: 8,
  } as ViewStyle,
  progressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 2,
  } as ViewStyle,
  progressText: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSecondary,
  } as TextStyle,
  taskItem: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  } as ViewStyle,
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  } as ViewStyle,
  taskTitle: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: colors.textPrimary,
  } as TextStyle,
  taskDescription: {
    fontSize: 12,
    lineHeight: 20,
    color: colors.textSecondary,
    marginBottom: 12,
  } as TextStyle,
  taskFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as ViewStyle,
  taskTime: {
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSecondary,
  } as TextStyle,
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  } as ViewStyle,
  statusText: {
    fontSize: 11,
    lineHeight: 16,
    textTransform: 'capitalize',
  } as TextStyle,
} as const;

// Task Add styles
export const taskAddStyles = {
  container: {
    flex: 1,
    backgroundColor: colors.white,
  } as ViewStyle,
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.white,
  } as ViewStyle,
  headerButton: {
    padding: 8,
  } as ViewStyle,
  headerRight: {
    flexDirection: 'row',
  } as ViewStyle,
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
  } as TextStyle,
  content: {
    flex: 1,
    padding: 16,
    backgroundColor: colors.white,
  } as ViewStyle,
  section: {
    marginBottom: 24,
  } as ViewStyle,
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 16,
    color: colors.textPrimary,
  } as TextStyle,
  input: {
    width: '100%',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 16,
    padding: 16,
    paddingLeft: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    color: colors.textPrimary,
    backgroundColor: colors.background,
  } as TextStyle,
  textArea: {
    height: 140,
    textAlignVertical: 'top',
  } as TextStyle,
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 16,
    borderStyle: 'dashed',
    backgroundColor: colors.background,
  } as ViewStyle,
  uploadText: {
    marginLeft: 8,
    fontSize: 16,
    color: colors.textPrimary,
  } as TextStyle,
  radioGroup: {
    gap: 10,
  } as ViewStyle,
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.background,
  } as ViewStyle,
  radioButtonActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(121, 128, 255, 0.1)',
  } as ViewStyle,
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.background,
  } as ViewStyle,
  checkboxActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(121, 128, 255, 0.1)',
  } as ViewStyle,
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.line,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  } as ViewStyle,
  checkboxChecked: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  } as ViewStyle,
  checkboxText: {
    fontSize: 16,
    color: colors.textPrimary,
  } as TextStyle,
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.white,
  } as ViewStyle,
  submitButton: {
    backgroundColor: colors.primary,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  } as ViewStyle,
  submitButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  } as TextStyle,
} as const;

// Footer styles
export const footerStyles = {
  menubarFooter: {
    paddingVertical: 10,
    paddingHorizontal: 26,
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: colors.textPrimary,
    shadowOffset: {
      width: 0,
      height: -8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 44,
    elevation: 8,
  } as ViewStyle,
  innerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  } as ViewStyle,
  footerSide: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '40%',
  } as ViewStyle,
  footerItem: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  } as ViewStyle,
  addTaskWrapper: {
    alignItems: 'center',
    width: '20%',
  } as ViewStyle,
  actionAddTask: {
    marginTop: -45,
    width: 64,
    height: 64,
    backgroundColor: colors.primary,
    borderRadius: 9999,
    justifyContent: 'center',
    alignItems: 'center',
  } as ViewStyle,
} as const;
